name: Relese

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare environment.firebase.ts
      run: |
        echo -e "\
        export const environment = {\n\
          apiKey: '${{ secrets.API_KEY }}',\n\
          authDomain: '${{ secrets.AUTH_DOMAIN }}',\n\
          databaseURL: '${{ secrets.DATABASE_URL }}',\n\
          projectId: '${{ secrets.PROJECT_ID }}',\n\
          storageBucket: '${{ secrets.STORAGE_BUCKET }}',\n\
          messagingSenderId: '${{ secrets.MESSAGING_SENDER_ID }}',\n\
          appId: '${{ secrets.APP_ID }}',\n\
          measurementId: '${{ secrets.MEASUREMENT_ID }}'\n\
        };" > ./src/environments/environment.firebase.ts

    - name: Install and Build
      run: |
        npm ci
        npm run build:gh-pages
      env:
        CI: true

    - name: Deploy 
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/takibi
